# Configurationfile BanGUI
# Version 1.0
# Author: Timeout

# Dies ist die normale Config.yml des Bansystems.
# Hier können Grundeinstellungen vorgenommen werden.

# Die ausgewählte Sprache des Plugins.
language: 'de_DE'

# BungeeCord-Support
bungeecord: true

# IP-Ban 
ip: true

#Used Databases
database: mysql

mysql:
  host: 'localhost'
  port: 3306
  database: 'bansystem'
  username: 'username'
  password: 'password'
  
file:
  path: '/databases'
  
  # Netty-Server
  client:
    # Address of your BungeeCord-Server
    host: '127.0.0.1'
    # Port in BungeeCord Config
    port: 8000