# Configurationfile BanGUI
# Version 1.0
# Author: Timeout

# Dies ist die normale Config.yml des Bansystems.
# Hier können Grundeinstellungen vorgenommen werden.

# Die ausgewählte Sprache des Plugins.
language: 'de_DE'

# BungeeCord-Support
bungeecord: true

mysql:
  host: 'localhost'
  port: 3306
  database: 'bansystem'
  username: 'username'
  password: 'password'