name: EasyBan-GUI
author: Timeout
version: 0.3
description: Eine GUI für das Bansystem

main: de.timeout.bukkit.ban.BanGUI

commands:
  ban:
    description: Bant einen Spieler
  mute:
    description: Mutet einen Spieler
  addreason:
    description: Fügt eine Reason hinzu
  delreason:
    description: Entfernt eine Reason
  unban:
    description: Entbannt einen Spieler
  unmute:
    description: Entmutet einen Spieler

permissions:
  easyban.ban:
    description: Die GUI-Ban Permission
  easyban.permaban:
    description: Die GUI-PermaBan Permission
  easyban.ignoreban:
    description: Die Ban-Ignore Permission
  easyban.ignoremute:
    description: Die Mute-Ignore Permission
  easyban.customban:
    description: Die GUI-CustomBan Permission
  easyban.mute:
    description: Die GUI-Mute Permission
  easyban.permamute:
    description: Die GUI-PermaMute Permission
  easyban.custommute:
    description: Die GUI-CustomMute Permission
  easyban.unmute:
    description: Die Unmute-Permission
  easyban.unban:
    description: Die Unban-Permission