# BanSystem Proxy Configuration
# Version 1.0
# Author: Timeout

# Das hier inst die Konfigurationsdatei für das BanSystem allgemein.
# Hier können verschiedene Einstellungen gemacht werden.

# Sprache des Systems
language: de_DE

# IP-Bans a player
ip: true

#Used Databases
database: mysql

# MySQL-Settings
mysql:
  host: "localhost"
  port: 3306
  database: "BanSystem"
  username: "Username"
  password: "Password"

file:
  path: '/databases'
  
  server:
    # Hostport
    port: 8000